### PR TITLE
Configure CI + CD

### PR DESCRIPTION
**Pull request by serpient**
# Setup CI/CD for API

### CODE REVIEW

**Comment by jayden** [comment]
In situations like this, it may be helpful to create a commit specifically for updating `.gitignore` and removing the files. It's a bit difficult to navigate the `Configure CI` commit since the diff is so large.

**Comment by zacholauson** [comment]
> In situations like this, it may be helpful to create a commit specifically for updating `.gitignore` and removing the files. It's a bit difficult to navigate the `Configure CI` commit since the diff is so large.

Agreed, it's pretty much impossible to get anything out of that `Configure CI` commit. My recommendation would be to soft-reset that commit, add the `.gitignore`, and make sure only valuable files are committed instead.

**Comment by serpient** [comment]
@zacholauson  @Jayden Commits have been rebased and cleaned up!

**Comment by zacholauson** [comment]
Looks good to me, @serpient

**Comment by zacholauson** [comment]
Although, should the controller stuff be in here?

**Comment by serpient** [comment]
> Although, should the controller stuff be in here?

We used the controller as a simple test to make sure everything was working once deployed

**Pull request merged**
